### ISSUE TITLE
Median host price not updating anymore

### ISSUE THREAD

**Issue by Fornax96** [S-anasol/siahub#17]
For the last 3 weeks the price per TB has been stuck on 750 SC, is there some kind of hardcoded limit that prevents it from going lower?
![image](https://user-images.githubusercontent.com/1247928/26871128-6ce13dd2-4b72-11e7-8480-89fee674788d.png)

On my own client I've also been watching the prices, but they have been hovering around 700 SC since a day or two. Here's what my Sia wallet is reporting right now:
```
$ siac renter prices
Renter Prices (estimated):
  Fees for Creating a Set of Contracts:   313 SC
  Download 1 TB:                          120.6 SC
  Store 1 TB for 1 Month:                 701.4 SC
  Upload 1 TB:                            105.7 SC
```

**Comment by S-anasol** [comment]
Since median is just "middle" of data it probably should not change too often or ever 😄 
Most hosts use default price 750 SC, so middle always 750.

So median not good for such stats, but tested 2-3 different algo and at least median stable one. 
Same time other algos doing some crazy jumps even if one small-storage host set price >9999.

If you have any idea how to calc it, let me know 👍 

here some variants which doesnt protect from jump or unchangeable like median value.
https://github.com/S-anasol/siahub/blob/master/app/Console/Commands/Network.php#L64-L68

Current values of different algos:

- raw median: 749.99999999952
- raw avg: 288700.12274011
- gb weight median: 1499.999999999
- gb weight avg: 92316.729788172
- storage gb: 1341697.3312374

**Comment by Fornax96** [comment]
I think the Sia wallet just uses the average of the the 50 highest scoring hosts. 

It would make most sense to just use the `renter prices` API to fetch the values every few minutes, since that reports the prices that renters actually pay when they are uploading and storing.

**Comment by S-anasol** [comment]
Looks like 50 random active and online hosts.
https://github.com/NebulousLabs/Sia/blob/9abac979dddb66f1de924eadcd51709fc23b975f/modules/renter/renter.go#L237
Didnt know about this api.
But hmmm random?

Simple avg over active hosts - same performed by me, but over all active not some 50 hosts.

This is raw avg on listed algo above.
288k SC current. Seems "unreal"

If we make it select random 50, it will be unpredictable and probably really random every time.

Executed few times on siahub wallet

![image](https://user-images.githubusercontent.com/1709666/26876877-b95f9514-4b90-11e7-8e45-c4f27c82b4a6.png)

Range 700-1200 SC/mo per TB.
Not the most accurate stats 😆

**Comment by Fornax96** [comment]
oh, that's pretty bad. Didn't realize it just uses randomly selected hosts. 

I think averaging the 50 highest scoring hosts will work better (and more stable).

**Comment by S-anasol** [comment]
Will try this later.
Maybe it will be stable/correct enough.

**Comment by Fornax96** [comment]
@DavidVorick How should prices be calculated? The `renter/prices` API is a much too random for this purpose.

**Comment by S-anasol** [comment]
So last formula work good as i see.
So i'll close this.
